/**
 * @format
 */

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import First from './First';
import Second from './Second';
import SafeareaViewexample from './SafeareaViewexample.js';
import ScrollViewExample from './ScrollViewExample.js';
import ViewExample from './ViewExample.js';
import ViewExample1 from './ViewExample1.js';
import styles from './styles.js';
import Demo from './Demo.js';
import calculator from './calculator.js';
import StyleSheet1 from './StyleSheet1.js';
import StyleSheet2 from './StyleSheet2';
import practice from './practice.js';
import practice01 from './practice01.js';
import SwitchExample from './SwitchExample'
import SliderExample from './SliderExample'
import SpinnerOverlayExample from './SpinnerOverlayExapmle'
import FlatlistExample from './FlatlistExample'
import CustomshapesExample from './CustomshapesExample'
import BottomViewExample from './BottomViewExample'
import onlongpress from './onlongpress';
import ButtonIcon from './ButtonIcon'
import Project007 from './Project007'
import PlaystoreProject from './PlaystoreProject'
import chaicode from './chaicode'
import flatcards from './flatcards'
import elevated from './component/elevated';
import fanncycard from './component/fancycard'
import ImageOpacity from './Tutionwork/ImageOpacity'
import Actioncard from './component/Actioncard'
import ZoomImage from './ZoomImage.js'
import TextInputNumber from './TextInputNumber';
import UppertoLower from './UppertoLower';
import contactlist from './component/contactlist';
import Arithmetic from './Tutionwork/Arithmetic';
import SimpleInterest from './Tutionwork/SimpleInterest';
import costprice from './Tutionwork/costprice';
import Makingcalculator from './Tutionwork/Makingcalculator';
import SquareExample from './SquareExample';
import NavExample from './NavExample';
import FirstPage from './pages/FirstPage';
import SecondPage from './pages/SecondPage';
import ThirdPage from './pages/ThirdPage';
import Page1 from './Navigation/Page1';
import Page2 from './Navigation/Page2';
import Page3 from './Navigation/Page3';
import FirstPages from './Pagess/FirstPages';
import SecondPages from './Pagess/SecondPages';
import NavigationExample from './NavigationExample';
import NavTabExample from './NavTabExample';
import ThirdPages from './Pagess/ThirdPages';
import HomeScreen from './BottomNavigation/HomeScreen';
import DetailsScreen from './BottomNavigation/DetailScreen';
import ProfileScreen from './BottomNavigation/ProfileScreen';
import SettingsScreen from './BottomNavigation/SettingScreen';
import NavBottomExample from './NavBottomExample';
import Homescreen from './Studentportal/Homescreen';
import Detailscreen from './Studentportal/Detailscreen';
import Profilescreen from './Studentportal/Profilescreen';
import Settingscreen from './Studentportal/Settingscreen';
// import NavBottom from './Studentportal/Navbottom';
import SplashScreen from './Studentportal/SplashScreen';
import RegisterScreen from './Studentportal/RegisterScreen';
import LoginScreen from './Studentportal/LoginScreen';
import StudentNav from './Studentportal/StudentNav';
import NavSchool from './NavSchool';
import FourthPage from './School/FourthPage';
import Home from './School/Home';
import Detail from './School/Detail';
import Profile from './School/Profile';
import Setting from './School/Setting';
import NavBottom from './NavBottom';
import Homework from './School/Homework';
import RadioButton from './RadioButton';
import RadioButtonFlatlist from './RadioButtonFlatlist';
import ShowEvent from './School/ShowEvent';
import EditEvent from './School/EditEvent';
AppRegistry.registerComponent(appName, () => NavSchool);
